sudo: required
services:
        - docker

before_install:
        - docker build -t ClaudiaB29/react-test -f ./client/Dockerfile.dev ./client

script:
        - docker run -e CI=true ClaudiaB29/react-test npm test

after_success:
        - docker build -t ClaudiaB29/multi-client ./client
        - docker build -t ClaudiaB29/multi-nginx ./nginx
        - docker build -t ClaudiaB29/multi-server ./server
        - docker build -t ClaudiaB29/multi-worker ./worker
          # Log in to the docker CLI
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
          # Take those images and push them to docker hub
        - docker push ClaudiaB29/multi-client
        - docker push ClaudiaB29/multi-nginx
        - docker push ClaudiaB29/multi-server
        - docker push Claudia B29/multi-worker
