sudo: required
services:
        - docker

before_install:
        - docker build -t claudi2909/react-test -f ./client/Dockerfile.dev ./client

script:
        - docker run -e CI=true claudi2909/react-test npm test

after_success:
        - docker build -t claudi2909/multi-client ./client
        - docker build -t claudi2909/multi-nginx ./nginx
        - docker build -t claudi2909/multi-server ./server
        - docker build -t claudi2909/multi-worker ./worker
          # Log in to the docker CLI
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
          # Take those images and push them to docker hub
        - docker push claudi2909/multi-client
        - docker push claudi2909/multi-nginx
        - docker push claudi2909/multi-server
        - docker push claudi2909/multi-worker
